print("EXAMPLE 1")
name = input("what is your name ")
print(f"hello {name} welcome to ct18")
print("today i will tell you a story")
print("but i need your help")
print("")
print("")
animal = input ("pick an animal: ")
location = input ("now a place or city: ")
home = input ("pick a cool thing in a house: ")
print("(:  (:  (:  (:  (:  (:  (:  (: (:  (:  (:  (: (:  (:  (:  (: (:  (:  (:  (: (:")
print(f"once upon a time there is a {animal} princess")
print(f" she lived in a tall tall tower in the humble Kingdom of {location}")
print("but were not done yet")
tragedy = input ("pick a tragic event: ")
print(" now back to the story")
print(f"this {tragedy} ended up setting her tower to flame")
print("and since then she has lived a life of bad luck one tragic event after another")
print(f"but when she was remodeling her Tower she got a {home}")
print("the end")